HEAD:
    port: 7890
    socks-port: 7891
    redir-port: 7892
    mixed-port: 7893
    tproxy-port: 7895
    ipv6: false
    mode: rule
    log-level: silent
    allow-lan: true
    external-controller: 0.0.0.0:9090
    secret: ""
    bind-address: "*"
    unified-delay: true
    profile:
      store-selected: true
    dns:
      enable: true
      ipv6: false
      enhanced-mode: redir-host
      listen: 0.0.0.0:7874
      nameserver:
        - 1.1.1.1
        - https://cloudflare-dns.com/dns-query
      default-nameserver:
        - 1.1.1.1
TEST_URL: http://cp.cloudflare.com/generate_204
CUSTOM_PROXY_GROUP:
- name: 🚀 Manual 1
  type: select
  manual: true
  rule: false
- name: 🚀 Manual 2
  type: select
  manual: true
  rule: false
- name: 🔯 Fallback
  type: fallback
  rule: false
- name: 🔮 Load Balancing
  type: load-balance
  rule: false